package color

import asposecells "github.com/aspose-cells/aspose-cells-go-cpp/v26"

// namedColorConstructors maps a normalized color name to the engine's
// constructor for that color.
//
// The toolkit resolves a color name through this table rather than through
// the engine's Color_FromName, which THROWS an uncaught C++ exception on a
// name it does not know. That exception crosses the cgo boundary and kills
// the process outright, so no amount of Go-side error handling can contain
// it — the name has to be validated before the engine ever sees it.
//
// The keys are the engine's own color constructors, normalized the way
// color.Resolve does (lower case, alphanumerics only), so the accepted
// vocabulary is exactly the engine's and the RGB values are the engine's own
// rather than a hand-copied table.
var namedColorConstructors = map[string]func() (*asposecells.Color, error){
	"aliceblue":            asposecells.Color_AliceBlue,
	"antiquewhite":         asposecells.Color_AntiqueWhite,
	"aqua":                 asposecells.Color_Aqua,
	"aquamarine":           asposecells.Color_Aquamarine,
	"azure":                asposecells.Color_Azure,
	"beige":                asposecells.Color_Beige,
	"bisque":               asposecells.Color_Bisque,
	"black":                asposecells.Color_Black,
	"blanchedalmond":       asposecells.Color_BlanchedAlmond,
	"blue":                 asposecells.Color_Blue,
	"blueviolet":           asposecells.Color_BlueViolet,
	"brown":                asposecells.Color_Brown,
	"burlywood":            asposecells.Color_BurlyWood,
	"cadetblue":            asposecells.Color_CadetBlue,
	"chartreuse":           asposecells.Color_Chartreuse,
	"chocolate":            asposecells.Color_Chocolate,
	"coral":                asposecells.Color_Coral,
	"cornflowerblue":       asposecells.Color_CornflowerBlue,
	"cornsilk":             asposecells.Color_Cornsilk,
	"crimson":              asposecells.Color_Crimson,
	"cyan":                 asposecells.Color_Cyan,
	"darkblue":             asposecells.Color_DarkBlue,
	"darkcyan":             asposecells.Color_DarkCyan,
	"darkgoldenrod":        asposecells.Color_DarkGoldenRod,
	"darkgray":             asposecells.Color_DarkGray,
	"darkgreen":            asposecells.Color_DarkGreen,
	"darkkhaki":            asposecells.Color_DarkKhaki,
	"darkmagenta":          asposecells.Color_DarkMagenta,
	"darkolivegreen":       asposecells.Color_DarkOliveGreen,
	"darkorange":           asposecells.Color_DarkOrange,
	"darkorchid":           asposecells.Color_DarkOrchid,
	"darkred":              asposecells.Color_DarkRed,
	"darksalmon":           asposecells.Color_DarkSalmon,
	"darkseagreen":         asposecells.Color_DarkSeaGreen,
	"darkslateblue":        asposecells.Color_DarkSlateBlue,
	"darkslategray":        asposecells.Color_DarkSlateGray,
	"darkturquoise":        asposecells.Color_DarkTurquoise,
	"darkviolet":           asposecells.Color_DarkViolet,
	"deeppink":             asposecells.Color_DeepPink,
	"deepskyblue":          asposecells.Color_DeepSkyBlue,
	"dimgray":              asposecells.Color_DimGray,
	"dodgerblue":           asposecells.Color_DodgerBlue,
	"firebrick":            asposecells.Color_FireBrick,
	"floralwhite":          asposecells.Color_FloralWhite,
	"forestgreen":          asposecells.Color_ForestGreen,
	"fuchsia":              asposecells.Color_Fuchsia,
	"gainsboro":            asposecells.Color_Gainsboro,
	"ghostwhite":           asposecells.Color_GhostWhite,
	"gold":                 asposecells.Color_Gold,
	"goldenrod":            asposecells.Color_GoldenRod,
	"gray":                 asposecells.Color_Gray,
	"green":                asposecells.Color_Green,
	"greenyellow":          asposecells.Color_GreenYellow,
	"honeydew":             asposecells.Color_HoneyDew,
	"hotpink":              asposecells.Color_HotPink,
	"indianred":            asposecells.Color_IndianRed,
	"indigo":               asposecells.Color_Indigo,
	"ivory":                asposecells.Color_Ivory,
	"khaki":                asposecells.Color_Khaki,
	"lavender":             asposecells.Color_Lavender,
	"lavenderblush":        asposecells.Color_LavenderBlush,
	"lawngreen":            asposecells.Color_LawnGreen,
	"lemonchiffon":         asposecells.Color_LemonChiffon,
	"lightblue":            asposecells.Color_LightBlue,
	"lightcoral":           asposecells.Color_LightCoral,
	"lightcyan":            asposecells.Color_LightCyan,
	"lightgoldenrodyellow": asposecells.Color_LightGoldenRodYellow,
	"lightgray":            asposecells.Color_LightGray,
	"lightgreen":           asposecells.Color_LightGreen,
	"lightpink":            asposecells.Color_LightPink,
	"lightsalmon":          asposecells.Color_LightSalmon,
	"lightseagreen":        asposecells.Color_LightSeaGreen,
	"lightskyblue":         asposecells.Color_LightSkyBlue,
	"lightslategray":       asposecells.Color_LightSlateGray,
	"lightsteelblue":       asposecells.Color_LightSteelBlue,
	"lightyellow":          asposecells.Color_LightYellow,
	"lime":                 asposecells.Color_Lime,
	"limegreen":            asposecells.Color_LimeGreen,
	"linen":                asposecells.Color_Linen,
	"magenta":              asposecells.Color_Magenta,
	"maroon":               asposecells.Color_Maroon,
	"mediumaquamarine":     asposecells.Color_MediumAquaMarine,
	"mediumblue":           asposecells.Color_MediumBlue,
	"mediumorchid":         asposecells.Color_MediumOrchid,
	"mediumpurple":         asposecells.Color_MediumPurple,
	"mediumseagreen":       asposecells.Color_MediumSeaGreen,
	"mediumslateblue":      asposecells.Color_MediumSlateBlue,
	"mediumspringgreen":    asposecells.Color_MediumSpringGreen,
	"mediumturquoise":      asposecells.Color_MediumTurquoise,
	"mediumvioletred":      asposecells.Color_MediumVioletRed,
	"midnightblue":         asposecells.Color_MidnightBlue,
	"mintcream":            asposecells.Color_MintCream,
	"mistyrose":            asposecells.Color_MistyRose,
	"moccasin":             asposecells.Color_Moccasin,
	"navajowhite":          asposecells.Color_NavajoWhite,
	"navy":                 asposecells.Color_Navy,
	"oldlace":              asposecells.Color_OldLace,
	"olive":                asposecells.Color_Olive,
	"olivedrab":            asposecells.Color_OliveDrab,
	"orange":               asposecells.Color_Orange,
	"orangered":            asposecells.Color_OrangeRed,
	"orchid":               asposecells.Color_Orchid,
	"palegoldenrod":        asposecells.Color_PaleGoldenRod,
	"palegreen":            asposecells.Color_PaleGreen,
	"paleturquoise":        asposecells.Color_PaleTurquoise,
	"palevioletred":        asposecells.Color_PaleVioletRed,
	"papayawhip":           asposecells.Color_PapayaWhip,
	"peachpuff":            asposecells.Color_PeachPuff,
	"peru":                 asposecells.Color_Peru,
	"pink":                 asposecells.Color_Pink,
	"plum":                 asposecells.Color_Plum,
	"powderblue":           asposecells.Color_PowderBlue,
	"purple":               asposecells.Color_Purple,
	"red":                  asposecells.Color_Red,
	"rosybrown":            asposecells.Color_RosyBrown,
	"royalblue":            asposecells.Color_RoyalBlue,
	"saddlebrown":          asposecells.Color_SaddleBrown,
	"salmon":               asposecells.Color_Salmon,
	"sandybrown":           asposecells.Color_SandyBrown,
	"seagreen":             asposecells.Color_SeaGreen,
	"seashell":             asposecells.Color_SeaShell,
	"sienna":               asposecells.Color_Sienna,
	"silver":               asposecells.Color_Silver,
	"skyblue":              asposecells.Color_SkyBlue,
	"slateblue":            asposecells.Color_SlateBlue,
	"slategray":            asposecells.Color_SlateGray,
	"snow":                 asposecells.Color_Snow,
	"springgreen":          asposecells.Color_SpringGreen,
	"steelblue":            asposecells.Color_SteelBlue,
	"tan":                  asposecells.Color_Tan,
	"teal":                 asposecells.Color_Teal,
	"thistle":              asposecells.Color_Thistle,
	"tomato":               asposecells.Color_Tomato,
	"turquoise":            asposecells.Color_Turquoise,
	"violet":               asposecells.Color_Violet,
	"wheat":                asposecells.Color_Wheat,
	"white":                asposecells.Color_White,
	"whitesmoke":           asposecells.Color_WhiteSmoke,
	"yellow":               asposecells.Color_Yellow,
	"yellowgreen":          asposecells.Color_YellowGreen,
}
